# All of the configuration realated to data ingestion

artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data-ingestion   
  train_data_path: artifacts/data-ingestion/train.csv
  test_data_path: artifacts/data-ingestion/test.csv
  raw_data_path: artifacts/data-ingestion/data.csv

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5